# Generated by Django 5.1 on 2024-11-14 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prn', models.IntegerField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.division')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_status', to='app.status')),
            ],
        ),
    ]
