# Generated by Django 5.1 on 2024-11-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_student_prn'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='stud@mitwpu.edu.in', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='phn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
